secuenceDiagram
participant user
participant browser
participant server
user->>browser: Type text and click "Save" button
Note right of browser: form submit event is triggered
browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note with form data
activate server
server->>browser: HTTP 302 Redirects to /notes
deactivate server
browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/notes
activate server
server-->>browser: HTML document
deactivate server
browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
activate server
server-->>browser: css file
deactivate server
browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
activate server
server-->>browser: the JavaScript file
deactivate server
Note right of browser: The browser starts executing the JavaScript code that fetches the JSON from the server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: [..., {"content": "CLEAN DATA", "date": "2025-08-03T04:31:27.737Z"} ]
    deactivate server

    Note right of browser: The browser executes the callback function that renders the notes

    browser-->user: Show the redered content
